/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programa.calculadora;

/**
 *
 * @author Pichau
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtN = new javax.swing.JSpinner();
        lblDiv = new javax.swing.JLabel();
        lblQuadrado = new javax.swing.JLabel();
        lblCubo = new javax.swing.JLabel();
        lblElevado = new javax.swing.JLabel();
        lblAbsoluto = new javax.swing.JLabel();
        lblResultadoDiv = new javax.swing.JLabel();
        lblResultadoQuadrado = new javax.swing.JLabel();
        lblResultadoCubo = new javax.swing.JLabel();
        lblResultadoElevado = new javax.swing.JLabel();
        lblResultadoAbsoluto = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadora.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Super Calculadora");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Informe um valor :");

        lblResultadoDiv.setForeground(new java.awt.Color(255, 0, 0));

        lblResultadoQuadrado.setForeground(new java.awt.Color(255, 0, 0));

        lblResultadoCubo.setForeground(new java.awt.Color(255, 0, 0));

        lblResultadoElevado.setForeground(new java.awt.Color(255, 0, 0));

        lblResultadoAbsoluto.setForeground(new java.awt.Color(255, 0, 0));

        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiv)
                    .addComponent(lblQuadrado)
                    .addComponent(lblCubo)
                    .addComponent(lblElevado)
                    .addComponent(lblAbsoluto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblResultadoDiv)
                                .addComponent(lblResultadoQuadrado)
                                .addComponent(lblResultadoCubo)
                                .addComponent(lblResultadoElevado)
                                .addComponent(lblResultadoAbsoluto))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCalc)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalc))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblResultadoDiv)
                                .addGap(18, 18, 18)
                                .addComponent(lblResultadoQuadrado)
                                .addGap(18, 18, 18)
                                .addComponent(lblResultadoCubo)
                                .addGap(18, 18, 18)
                                .addComponent(lblResultadoElevado)
                                .addGap(18, 18, 18)
                                .addComponent(lblResultadoAbsoluto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiv)
                                .addGap(18, 18, 18)
                                .addComponent(lblQuadrado)
                                .addGap(18, 18, 18)
                                .addComponent(lblCubo)
                                .addGap(18, 18, 18)
                                .addComponent(lblElevado)
                                .addGap(18, 18, 18)
                                .addComponent(lblAbsoluto))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        int n = Integer.parseInt(txtN.getValue().toString());
        
        int raizQuadrada = (int) Math.sqrt(n);
        int raizCubica = (int) Math.cbrt(n);
        int divisao = (int) n/2;
        int elevado = (int) Math.pow(n, 3);
        int absoluto = (int) Math.abs(n);
        
        lblDiv.setText("Resto da divisão por dois");
        lblQuadrado.setText("Raíz quadrada");
        lblCubo.setText("Raíz cubica");
        lblElevado.setText("Elevado ao cubo");
        lblAbsoluto.setText("Valor absoluto");
        
        lblResultadoDiv.setText(Integer.toString(divisao));
        lblResultadoQuadrado.setText(Integer.toString(raizQuadrada));
        lblResultadoCubo.setText(Integer.toString(raizCubica));
        lblResultadoElevado.setText(Integer.toString(elevado));
        lblResultadoAbsoluto.setText(Integer.toString(absoluto));
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAbsoluto;
    private javax.swing.JLabel lblCubo;
    private javax.swing.JLabel lblDiv;
    private javax.swing.JLabel lblElevado;
    private javax.swing.JLabel lblQuadrado;
    private javax.swing.JLabel lblResultadoAbsoluto;
    private javax.swing.JLabel lblResultadoCubo;
    private javax.swing.JLabel lblResultadoDiv;
    private javax.swing.JLabel lblResultadoElevado;
    private javax.swing.JLabel lblResultadoQuadrado;
    private javax.swing.JSpinner txtN;
    // End of variables declaration//GEN-END:variables
}
